### ISSUE TITLE
crash when I load a wav file through the screen and don't load wave file when I drag them on to the pad but it does with SND file.

### ISSUE THREAD

**Issue by lv2lrn4lf** [izzyreal/vmpc-docs#5]
crash when I load a wav file through the screen and don't load wave file when I drag them on to the pad but it does with SND file.

So when I tried to load a wav file through the screen display load menu, it crash, and when I drag a wav file to a pad it does not load but it handle SND file type exactly as it should.

**Comment by izzyreal** [comment]
HI @lv2lrn4lf, please open a ticket in https://github.com/izzyreal/mpc and attach the failing WAV file. Thanks!
